/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  14601: {
    ForgeLuckyInstant: {
      address: "0xb2bcc9a63ad3368887b80d09971135c2010a37d9",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "randomGeneratorAddr",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "nonpayable"
        },
        {
          type: "receive",
          stateMutability: "payable"
        },
        {
          type: "function",
          name: "FEE_BASE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "GRAND_PRIZE_POOL_RATIO",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "GRAND_PRIZE_RATE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "GROWTH_FUND_RATIO",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "MAX_BATCH_SIZE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "MEDIUM_PRIZE_POOL_RATIO",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "MEDIUM_PRIZE_RATE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "PLATFORM_FEE_RATE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "SMALL_PRIZE_POOL_RATIO",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "SMALL_PRIZE_RATE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "SUPER_GRAND_POOL_RATIO",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "SUPER_GRAND_RATE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "TICKET_PRICE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "adminBatchDraw",
          inputs: [
            {
              name: "tokenIds",
              type: "uint256[]",
              internalType: "uint256[]"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address"
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "batchBuyTickets",
          inputs: [
            {
              name: "count",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "payable"
        },
        {
          type: "function",
          name: "batchBuyTicketsWithBalance",
          inputs: [
            {
              name: "count",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "batchDrawSpecificTickets",
          inputs: [
            {
              name: "tokenIds",
              type: "uint256[]",
              internalType: "uint256[]"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "batchDrawUserTickets",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "buyTicket",
          inputs: [],
          outputs: [],
          stateMutability: "payable"
        },
        {
          type: "function",
          name: "buyTicketWithBalance",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "canDrawTicket",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "claimPrize",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable"
        },
        {
          type: "function",
          name: "drawTicket",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getPoolStats",
          inputs: [],
          outputs: [
            {
              name: "superGrandPool",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "grandPool",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "mediumPool",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "smallPool",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "totalPool",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getProbabilityStats",
          inputs: [],
          outputs: [
            {
              name: "superGrandRate",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "grandRate",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "mediumRate",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "smallRate",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "totalWinRate",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "noWinRate",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "pure"
        },
        {
          type: "function",
          name: "getSystemStats",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ForgeLuckyInstant.SystemStats",
              components: [
                {
                  name: "totalSales",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "platformFees",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "growthFund",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "totalTickets",
                  type: "uint256",
                  internalType: "uint256"
                }
              ]
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getTicket",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ForgeLuckyInstant.Ticket",
              components: [
                {
                  name: "purchaseTime",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "isDrawn",
                  type: "bool",
                  internalType: "bool"
                },
                {
                  name: "prizeLevel",
                  type: "uint8",
                  internalType: "enum ForgeLuckyInstant.PrizeLevel"
                },
                {
                  name: "prizeAmount",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "isClaimed",
                  type: "bool",
                  internalType: "bool"
                }
              ]
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getUserInfo",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "totalTickets",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "totalWinnings",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "claimableAmount",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "purchaseAmount",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getUserTickets",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getUserUndrawnTickets",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "undrawnTickets",
              type: "uint256[]",
              internalType: "uint256[]"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getUserUnclaimedWinningTickets",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "unclaimedTickets",
              type: "uint256[]",
              internalType: "uint256[]"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address"
            },
            {
              name: "operator",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "pause",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "paused",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address"
            },
            {
              name: "to",
              type: "address",
              internalType: "address"
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address"
            },
            {
              name: "to",
              type: "address",
              internalType: "address"
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address"
            },
            {
              name: "approved",
              type: "bool",
              internalType: "bool"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4"
            }
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "tokenByIndex",
          inputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "tokenOfOwnerByIndex",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address"
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address"
            },
            {
              name: "to",
              type: "address",
              internalType: "address"
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "unpause",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "userBalances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "withdrawAllBalance",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "withdrawBalance",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        }
      ],
      inheritedFunctions: {},
      deployedOnBlock: 5,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;